### ISSUE TITLE
Villages have no contents.

### ISSUE THREAD

**Issue by Gbergz** [End-of-Days-Modpack-Team/Eclipse#6]
Villages has no doors, blacksmith is missing its Chest & no windows either.
All farms are missing their seeds/plants.

Screenshot: 
[Imgur](https://i.imgur.com/mItxYgj.png)

Forge version: 14.23.0.2546

**Comment by ItsApache** [comment]
It's due to the HCVillages module added by BetterWithMods.

# Makes it so villages with in the reaches of the spawn zone are abandoned and gradually gain more resources the further out. What this means to be gained by the player.
    B:HCVillages=true
